main:
    - identifier: home
      name: Home
      url: /
      weight: -100
      params:
          ### For demonstration purpose, the home link will be open in a new tab
          newTab: flase
          icon: home

social:
    - identifier: github
      name: GitHub
      url: https://github.com/rento666
      weight: 1
      params:
          icon: brand-github

    - identifier: twitter
      name: Twitter
      url: https://x.com/CaiHongTuu
      weight: 2
      params:
          icon: brand-twitter
    
    - identifier: email
      name: Email
      url: mailto:admin_reply@caihongtu.asia
      weight: 3
      params:
          icon: brand-email
              
    - identifier: rss
      name: Rss
      url: /index.xml
      weight: 4
      params:
          icon: rss
